# Github uses redcarpet internally, we will use it here
markdown: redcarpet
redcarpet:
  extensions: ["smart"]
pygments: true
permalink: /posts/:title
title: I am Ashish, an IIT Madras grad, a serial but not so succesfull entrepreneur, looking for a job now.
# Note leave off trailing /
production_url : http://pocha.rocks
description: Personal site of Ashish Kumar Sharma aka Pocha
author:
  name: Ashish Sharma
  github: pocha
  twitter: pocha
  linkedin: http://linkedin.com/in/thinkingpocha
  email: pocha.sharma@gmail.com
  phone: +91 95 3838 4545
